### ISSUE TITLE
installation with Cabal fails

### ISSUE THREAD

**Issue by pauloud** [tomferon/morph#1]
My installation with Cabal failed on Mac OS 10.14 while trying to install Spock, morph building failed with
` src/Control/Monad/Trans/Compose.hs:60:7: error:
    Not in scope: type constructor or class ‘MonadFail’
   |
60 |     , MonadFail
   |       ^^^^^^^^^ `
   And when I'm trying to intsall only morph I've got a problem with postgresql package
   
   ```
/Users/me/.cabal/logs/ghc-8.6.3/pstgrsql-lbpq-0.9.4.3-198df10e.log
):
[1 of 1] Compiling Main             ( /var/folders/y2/0hb8j18x2mx699f66shljych0000gn/T/cabal-install.-37497/dist-newstyle/tmp/src-37498/postgresql-libpq-0.9.4.3/dist/setup/setup.hs, /var/folders/y2/0hb8j18x2mx699f66shljych0000gn/T/cabal-install.-37497/dist-newstyle/tmp/src-37498/postgresql-libpq-0.9.4.3/dist/setup/Main.o )
Linking /var/folders/y2/0hb8j18x2mx699f66shljych0000gn/T/cabal-install.-37497/dist-newstyle/tmp/src-37498/postgresql-libpq-0.9.4.3/dist/setup/setup ...
Configuring postgresql-libpq-0.9.4.3...
setup: The program 'pg_config' is required but it could not be found.
```
I don't know wether those two errors have the same cause or not.

**Comment by tomferon** [comment]
I somehow haven't seen any notification about this issue before but for what it's worth after such a long time, the first error you saw was not about morph but about hackage.haskell.org/package/mmorph (with two m's).
